### ISSUE TITLE
Proxy remaining calls of xud's grpc, including POST+socket

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker-api#4]
Currently only `GET` are supported. This is about adding the missing POST calls and socket (compare https://github.com/ExchangeUnion/xud-socketio).

**Comment by kilrau** [comment]
Depends on prio from https://github.com/ExchangeUnion/xud-ui side

**Comment by krrprr** [comment]
Needed by https://github.com/ExchangeUnion/xud-ui/issues/29

**Comment by kilrau** [comment]
As the [console view](ExchangeUnion/xud-ui#29) is using the socketio, we'll implement the remaining calls step-by-step when we need them for the views. Thx @krrprr
